/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;


import clases.Ascensor;
import clases.Auto;
import clases.Camioneta;
import clases.Moto;
import clases.Planta;
import clases.Plaza;
import clases.Ticket;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Bianca Sozzi
 */
public class IngresarVehiculo extends javax.swing.JFrame{

    /**
     * Creates new form IngresarVehiculo
     */
    private String tipoSeleccionado;
    private Ticket ticket = new Ticket();
    public void AsignarAscensor(){
        for(int i = 0; i < Estacionamiento.getAscensores().size(); i++){
                Ascensor asc = Estacionamiento.getAscensores().get(i);
                if(asc.getEsta().getNombre().equals("libre")){
                    ticket.setSubeEn(asc);
                    System.out.println("sube en:"+ticket.getSubeEn().getNumero());
                    i= Estacionamiento.getAscensores().size();
                    asc.setEsta(Estacionamiento.getEa2());
                }
        }
    }
    public void AsignarPlaza(){
        for(int i = 0; i< Estacionamiento.getPlantas().size(); i++){
            Planta planta= Estacionamiento.getPlantas().get(i);
                for(int j = 0; j< planta.getContiene().size(); j++){
                    Plaza plaza = planta.getContiene().get(j);
                    System.out.println(plaza.getNumero());
                    if(plaza.getEsta().getNombre().equals("libre")){
                        j= planta.getContiene().size();
                        i= Estacionamiento.getPlantas().size();
                        ticket.setEstacionadoEn(plaza);
                        System.out.println("estacionado en:" + ticket.getEstacionadoEn().getNumero());
                        plaza.setEsta(Estacionamiento.getEstadoPlazaOcupada());
                        System.out.println(plaza.getEsta().getNombre());
                    }
                }
        
        }
    }
    
    public IngresarVehiculo() {
        initComponents();
        setTitle("Ingresar Vehículo");
        setLocationRelativeTo(null);
        setResizable(false);
        //Fecha
        SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");
        String dia= date.format(new Date());
        //System.out.println(dia);
        fecha.setText(dia);
        //Hora
        SimpleDateFormat hora = new SimpleDateFormat("HH:mm");
        String hEntrada = hora.format(new Date());
        //System.out.println(hEntrada);
        horaE.setText(hEntrada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TerminarIngreso = new javax.swing.JButton();
        tipoVehiculo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patenteTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        horaE = new javax.swing.JLabel();
        TerminarIngreso1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingreso");
        jLabel1.setPreferredSize(new java.awt.Dimension(160, 40));

        TerminarIngreso.setText("TERMINAR");
        TerminarIngreso.setPreferredSize(new java.awt.Dimension(85, 30));
        TerminarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarIngresoActionPerformed(evt);
            }
        });

        tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "AUTO", "CAMIONETA", "MOTO" }));
        tipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVehiculoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tipo Vehículo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patente");

        patenteTxt.setPreferredSize(new java.awt.Dimension(85, 20));
        patenteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patenteTxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fecha");

        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hora Entrada");

        horaE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horaE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TerminarIngreso1.setText("CANCELAR");
        TerminarIngreso1.setPreferredSize(new java.awt.Dimension(85, 30));
        TerminarIngreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarIngreso1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TerminarIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TerminarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(horaE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patenteTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(patenteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(horaE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TerminarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TerminarIngreso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerminarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarIngresoActionPerformed
        
       //Instanciar vehiculo y guardar la información
        

        
        if(tipoSeleccionado == "AUTO"){
            Auto auto = new Auto(patenteTxt.getText());
            Estacionamiento.addAuto(auto);
            AsignarAscensor();
            AsignarPlaza();
            ticket.setPerteneceA(auto);
            /*for(int i=0; i< Estacionamiento.getAutos().size(); i++){
            System.out.println(Estacionamiento.getAutos().get(i).getPatente());
            System.out.println(Estacionamiento.getAutos().get(i).getTarifa());
                System.out.println(Estacionamiento.getAutos().get(0).getPatente());
            }*/
        }else{
            if(tipoSeleccionado == "CAMIONETA"){
                Camioneta camioneta = new Camioneta(patenteTxt.getText());
                Estacionamiento.addCamioneta(camioneta);
                AsignarAscensor();
                AsignarPlaza();
                ticket.setPerteneceA(camioneta);
            }else{
                Moto moto = new Moto(patenteTxt.getText());
                Estacionamiento.addMoto(moto);
                AsignarAscensor();
                AsignarPlaza();
                ticket.setPerteneceA(moto);
            }
        }
        
        
        ticket.setFecha(fecha.getText());
        ticket.setHoraEntrada(horaE.getText());
        
        Estacionamiento.mantenerOcupado();
        /*System.out.println(ticket.getFecha());
        System.out.println(ticket.getHoraEntrada());*/
        Estacionamiento.addTicket(ticket);
        // Ver Ticket
        TicketPantalla ticketP = new TicketPantalla(ticket);
        ticketP.setVisible(true);
        dispose();
        
       
        
        
        
    }//GEN-LAST:event_TerminarIngresoActionPerformed

    private void tipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVehiculoActionPerformed
 
        tipoSeleccionado = (String) tipoVehiculo.getSelectedItem();
        //System.out.println(tipoSeleccionado);
    }//GEN-LAST:event_tipoVehiculoActionPerformed

    private void patenteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patenteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patenteTxtActionPerformed

    private void TerminarIngreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarIngreso1ActionPerformed
        // TODO add your handling code here:
        PantallaPrincipal pp = new PantallaPrincipal();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_TerminarIngreso1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TerminarIngreso;
    private javax.swing.JButton TerminarIngreso1;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel horaE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patenteTxt;
    private javax.swing.JComboBox tipoVehiculo;
    // End of variables declaration//GEN-END:variables

}
