/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamiento;

import clases.Auto;
import clases.Ticket;
import clases.Vehiculo;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Bianca Sozzi
 */
public class RetirarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form RetirarVehiculo
     
     */
    private String tipoSeleccionado;
    private Vehiculo aRetirar;
          
    public RetirarVehiculo() {
        initComponents();
        setTitle("Retirar Vehículo");
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(400,300);
    }
    public void eliminarVehiculo(Ticket t){
        if(tipoSeleccionado == "AUTO"){
            for(int i=0; i<Estacionamiento.getAutos().size(); i++){
                if(t.getPerteneceA().getPatente().equals(Estacionamiento.getAutos().get(i).getPatente())){
                    Estacionamiento.getAutos().remove(i);
                    System.out.println("Eliminado");
                }
            }
        }else{
            if(tipoSeleccionado=="CAMIONETA"){
                for(int i=0; i<Estacionamiento.getCamionetas().size();i++){
                    if(t.getPerteneceA().getPatente().equals(Estacionamiento.getCamionetas().get(i).getPatente())){
                        Estacionamiento.getAutos().remove(i);
                    }
                }
            }else{
                for(int i=0; i<Estacionamiento.getMotos().size();i++){
                    if(t.getPerteneceA().getPatente().equals(Estacionamiento.getMotos().get(i).getPatente())){
                        Estacionamiento.getMotos().remove(i);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patente = new javax.swing.JTextField();
        buscarTicket = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        patenteR = new javax.swing.JLabel();
        tipoVehiculoR = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnCancelarEgreso = new javax.swing.JButton();
        confirmarEgreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Egreso");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patente");
        jLabel2.setPreferredSize(new java.awt.Dimension(85, 14));

        patente.setPreferredSize(new java.awt.Dimension(85, 20));
        patente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patenteActionPerformed(evt);
            }
        });

        buscarTicket.setText("BUSCAR");
        buscarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarTicketActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Patente");
        jLabel3.setPreferredSize(new java.awt.Dimension(85, 14));

        patenteR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patenteR.setPreferredSize(new java.awt.Dimension(85, 20));

        tipoVehiculoR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar...", "AUTO", "CAMIONETA", "MOTO" }));
        tipoVehiculoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVehiculoRActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tipo Vehiculo");
        jLabel5.setPreferredSize(new java.awt.Dimension(85, 14));

        btnCancelarEgreso.setText("CANCELAR");
        btnCancelarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEgresoActionPerformed(evt);
            }
        });

        confirmarEgreso.setText("CONFIRMAR");
        confirmarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEgresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(patente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoVehiculoR, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patenteR, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancelarEgreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmarEgreso))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarTicket)
                        .addGap(149, 149, 149)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoVehiculoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buscarTicket)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patenteR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEgreso)
                    .addComponent(confirmarEgreso))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patenteActionPerformed

    private void buscarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarTicketActionPerformed
        
        if(tipoSeleccionado == "AUTO"){
            for(int i = 0; i< Estacionamiento.getAutos().size(); i++){
               //System.out.println(Estacionamiento.getAutos().get(i).getPatente());
               //System.out.println(patenteAuto);
               if(Estacionamiento.getAutos().get(i).getPatente().equals(patente.getText())){
                    //System.out.println("Entro");
                    aRetirar = Estacionamiento.getAutos().get(i);   
                    //System.out.println(aRetirar.getPatente());
                }
            }
        }else{
            if(tipoSeleccionado == "CAMIONETA"){
                for(int i = 0 ; i < Estacionamiento.getCamionetas().size(); i++){
                    if(Estacionamiento.getCamionetas().get(i).getPatente().equals(patente.getText())){
                        aRetirar = Estacionamiento.getCamionetas().get(i);
                        //System.out.println(aRetirar.getPatente());
                    }
                }
            }else{
                for(int i = 0 ; i < Estacionamiento.getMotos().size(); i++){
                    if(Estacionamiento.getMotos().get(i).getPatente().equals(patente.getText())){
                        aRetirar = Estacionamiento.getMotos().get(i);
                        //System.out.println(aRetirar.getPatente());
                    }
                }
            }
        }
        patenteR.setText(aRetirar.getPatente());
    }//GEN-LAST:event_buscarTicketActionPerformed

    private void tipoVehiculoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVehiculoRActionPerformed
        tipoSeleccionado = (String) tipoVehiculoR.getSelectedItem();
        //System.out.println(tipoSeleccionado);// TODO add your handling code here:
    }//GEN-LAST:event_tipoVehiculoRActionPerformed

    private void btnCancelarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEgresoActionPerformed
        PantallaPrincipal pp = new PantallaPrincipal();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarEgresoActionPerformed

    private void confirmarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEgresoActionPerformed
        for(int i = 0; i < Estacionamiento.getTickets().size(); i++){
            Ticket ticket = Estacionamiento.getTickets().get(i);
            if(ticket.getPerteneceA().getPatente().equals(patente.getText())){
                //Hora
                SimpleDateFormat hora = new SimpleDateFormat("HH:mm");
                String hSalida = hora.format(new Date());
                //System.out.println(hSalida);
                ticket.setHoraSalida(hSalida);
                TicketPantalla ticketP = new TicketPantalla(ticket);
                ticketP.setVisible(true);
                ticket.getEstacionadoEn().setEsta(Estacionamiento.getEstadoPlazaLibre());
                eliminarVehiculo(ticket);
                Estacionamiento.getTickets().remove(i);
                dispose();
    
            }
        }
        
        
    }//GEN-LAST:event_confirmarEgresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetirarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetirarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetirarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetirarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetirarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEgreso;
    private javax.swing.JButton buscarTicket;
    private javax.swing.JButton confirmarEgreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField patente;
    private javax.swing.JLabel patenteR;
    private javax.swing.JComboBox tipoVehiculoR;
    // End of variables declaration//GEN-END:variables
}
